ALTER TABLE "Task" ADD COLUMN "addon2Name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Task" ADD COLUMN "addon2FrequencyDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "addon2Points" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Task" ADD COLUMN "addon2LastDoneAt" TIMESTAMP(3);
